# Generated by Django 4.0.6 on 2022-07-10 03:22

from django.db import migrations, models
import store_app.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomColor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(default='Color Nickname', max_length=50, unique=True)),
                ('code', models.CharField(default='#000000', max_length=9, validators=[store_app.models.custom_color_format_validator])),
            ],
        ),
    ]
