# Generated by Django 4.0.6 on 2022-07-10 22:37

import datetime
from decimal import Decimal
from django.db import migrations, models
import store_app.fields


class Migration(migrations.Migration):

    dependencies = [
        ('store_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=256, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ClothingCollection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=256)),
                ('year', models.CharField(default='2022', max_length=4)),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='uploads/collections/')),
            ],
        ),
        migrations.CreateModel(
            name='GlobalModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=False)),
                ('mx_value', store_app.fields.CurrencyDecimalField(decimal_places=4, default=Decimal('0.00'), max_digits=19)),
                ('us_sales_taxes', store_app.fields.CurrencyDecimalField(decimal_places=4, default=Decimal('0.00'), max_digits=19)),
                ('last_updated', models.DateField(default=datetime.date.today)),
            ],
        ),
        migrations.CreateModel(
            name='ClothingProducts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=256, unique=True)),
                ('code', models.CharField(default='', max_length=50)),
                ('base_pricing', store_app.fields.CurrencyDecimalField(decimal_places=4, default=Decimal('0.00'), max_digits=19)),
                ('available_colors', models.ManyToManyField(related_name='clothing_products', to='store_app.customcolor')),
                ('categories', models.ManyToManyField(related_name='clothing_products', to='store_app.category')),
                ('collections', models.ManyToManyField(related_name='clothing_products', to='store_app.clothingcollection')),
            ],
        ),
    ]
