# Generated by Django 4.0.6 on 2022-07-10 23:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store_app', '0003_alter_category_options_category_image'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ClothingProducts',
            new_name='ClothingProduct',
        ),
        migrations.CreateModel(
            name='ClothingProductImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='uploads/products/')),
                ('type_of_image', models.CharField(choices=[('PRIMARY', 'PRIMARY'), ('SECONDARY', 'SECONDARY'), ('EXTRA', 'EXTRA')], default='EXTRA', max_length=50)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store_app.clothingproduct')),
            ],
        ),
    ]
