# Generated by Django 4.0.6 on 2022-07-10 23:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store_app', '0004_rename_clothingproducts_clothingproduct_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ClothingProductImages',
            new_name='ClothingProductImage',
        ),
    ]
