# Generated by Django 4.0.6 on 2022-07-31 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_app', '0006_category_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clothingproduct',
            name='available_colors',
            field=models.ManyToManyField(related_name='clothing_products', related_query_name='clothing_products', to='store_app.customcolor'),
        ),
        migrations.AlterField(
            model_name='clothingproduct',
            name='categories',
            field=models.ManyToManyField(related_name='clothing_products', related_query_name='clothing_products', to='store_app.category'),
        ),
        migrations.AlterField(
            model_name='clothingproduct',
            name='collections',
            field=models.ManyToManyField(related_name='clothing_products', related_query_name='clothing_products', to='store_app.clothingcollection'),
        ),
    ]
