# Generated by Django 4.0.6 on 2022-08-13 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_app', '0007_alter_clothingproduct_available_colors_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clothingproduct',
            name='tag',
            field=models.CharField(choices=[('SHIRT', 'SHIRT'), ('PANTS', 'PANTS'), ('DRESS', 'DRESS')], default='SHIRT', max_length=50),
        ),
    ]
