# Generated by Django 4.0.6 on 2022-08-14 17:47

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion
import store_app.fields


class Migration(migrations.Migration):

    dependencies = [
        ('store_app', '0008_clothingproduct_tag'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_amount', store_app.fields.CurrencyDecimalField(decimal_places=4, default=Decimal('0.00'), max_digits=19)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('ip_address', models.GenericIPAddressField()),
                ('token', models.CharField(blank=True, default='', max_length=256)),
            ],
        ),
        migrations.AddField(
            model_name='clothingproduct',
            name='amount_sold',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='ProductVariation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(default='S', max_length=50)),
                ('sleeve', models.CharField(blank=True, default='None', max_length=50)),
                ('quantity', models.IntegerField(default=1)),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store_app.cart')),
                ('principal_color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store_app.customcolor')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store_app.clothingproduct')),
            ],
        ),
    ]
