# Generated by Django 4.0.6 on 2022-08-18 02:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store_app', '0009_cart_clothingproduct_amount_sold_productvariation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productvariation',
            name='cart',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='store_app.cart'),
        ),
    ]
