# Generated by Django 4.0.6 on 2022-08-28 23:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store_app', '0013_remove_order_zip_code_address_zip_code_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='commnets',
            new_name='comments',
        ),
    ]
