# Generated by Django 4.0.6 on 2022-11-09 03:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store_app', '0014_rename_commnets_order_comments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='total_amount',
        ),
        migrations.AlterField(
            model_name='productvariation',
            name='cart',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_variation_set', to='store_app.cart'),
        ),
    ]
