# Generated by Django 4.0.6 on 2022-11-09 05:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store_app', '0015_remove_cart_total_amount_alter_productvariation_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='shipping_tracking_id',
            field=models.CharField(blank=True, default='', max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='shipping_address',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='store_app.address'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('ORDEN_CREADA', 'ORDEN_CREADA'), ('PEDIDO_A_MEXICO', 'PEDIDO_A_MEXICO'), ('EN_CAMINO', 'EN_CAMINO'), ('ENTREGADO', 'ENTREGADO'), ('CANCELADO', 'CANCELADO'), ('REFUND', 'REFUND')], default='ORDEN_CREADA', max_length=256),
        ),
    ]
