# Generated by Django 4.0.6 on 2022-12-10 17:18

from decimal import Decimal
from django.db import migrations, models
import store_app.fields


class Migration(migrations.Migration):

    dependencies = [
        ('store_app', '0016_order_shipping_tracking_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='other_costs',
            field=store_app.fields.CurrencyDecimalField(decimal_places=4, default=Decimal('0.00'), max_digits=19),
        ),
        migrations.AddField(
            model_name='order',
            name='production_cost',
            field=store_app.fields.CurrencyDecimalField(decimal_places=4, default=Decimal('0.00'), max_digits=19),
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_company',
            field=models.CharField(choices=[('UPS', 'UPS'), ('FedEx', 'FedEx'), ('Other', 'Other')], default='UPS', max_length=50),
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_cost',
            field=store_app.fields.CurrencyDecimalField(decimal_places=4, default=Decimal('0.00'), max_digits=19),
        ),
    ]
