# Generated by Django 4.0.6 on 2022-12-10 17:39

from decimal import Decimal
from django.db import migrations
import store_app.fields


class Migration(migrations.Migration):

    dependencies = [
        ('store_app', '0017_order_other_costs_order_production_cost_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='production_cost',
        ),
        migrations.AddField(
            model_name='clothingproduct',
            name='production_cost',
            field=store_app.fields.CurrencyDecimalField(decimal_places=4, default=Decimal('0.00'), max_digits=19),
        ),
    ]
